// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");

function netlifyResponse(statusCode, body) {
  return {
          body: JSON.stringify(body),
          headers: Js_dict.fromArray([[
                  "content-type",
                  "application/json"
                ]]),
          statusCode: statusCode
        };
}

function handler($$event, context) {
  var body = $$event.body;
  if (body !== undefined) {
    return netlifyResponse(200, body);
  } else {
    return netlifyResponse(501, "Empty request body.");
  }
}

exports.netlifyResponse = netlifyResponse;
exports.handler = handler;
/* No side effect */
